version: '3.8'

services:
  lan-chat:
    image: hibernathan1212/lan-chat:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lan-chat-app
    # ports:
    #   - "3000:3000"
    network_mode: host
    volumes: 
      - chat_data:/data
    environment:
      - PORT=3000
      - DB_PATH=/data/chat.db
    restart: unless-stopped

volumes:
  chat_data: