services:
  lan-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lan-chat-app
    # ports:
    #   - "3000:3000"
    network_mode: host
    volumes: 
      - chat_data:/data
    environment:
      - PORT=3000
      - DB_PATH=/data/chat.db

volumes:
  chat_data: